import type { Site } from "./model";

// Source review and URL checks: README.md
export const categories = ["开发", "AI", "工具", "阅读"];
export const presetSites: Site[] = [
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com",
    category: "开发",
    description: "代码与开源项目",
    tags: ["代码", "开源"],
    icon: "G",
  },
  {
    id: "mdn",
    name: "MDN",
    url: "https://developer.mozilla.org/zh-CN/",
    category: "开发",
    description: "Web 开发文档",
    tags: ["文档", "Web"],
    icon: "M",
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    url: "https://huggingface.co",
    category: "AI",
    description: "模型、数据集与应用",
    tags: ["模型"],
    icon: "H",
  },
  {
    id: "tools",
    name: "工具箱",
    url: "https://tool.draco.dev",
    category: "工具",
    description: "日常实用工具",
    tags: ["工具"],
    icon: "T",
  },
  {
    id: "hn",
    name: "Hacker News",
    url: "https://news.ycombinator.com",
    category: "阅读",
    description: "科技与开发者社区",
    tags: ["科技"],
    icon: "Y",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    url: "https://www.deepseek.com/",
    category: "AI",
    description: "对话、推理与模型开发入口",
    tags: ["AI", "网站"],
    icon: "D",
  },
  {
    id: "kimi",
    name: "Kimi",
    url: "https://www.kimi.com/",
    category: "AI",
    description: "阅读材料、检索信息与辅助创作",
    tags: ["AI", "网站"],
    icon: "K",
  },
  {
    id: "doubao",
    name: "豆包",
    url: "https://www.doubao.com/",
    category: "AI",
    description: "日常问答与多模态内容助手",
    tags: ["AI", "网站"],
    icon: "豆",
  },
  {
    id: "cursor",
    name: "Cursor",
    url: "https://cursor.com/",
    category: "开发",
    description: "在代码编辑器中协作编程",
    tags: ["开发", "网站"],
    icon: "C",
  },
  {
    id: "dify",
    name: "Dify",
    url: "https://dify.ai/",
    category: "AI",
    description: "搭建模型应用与工作流",
    tags: ["AI", "网站"],
    icon: "D",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    url: "https://openrouter.ai/",
    category: "AI",
    description: "通过统一接口连接多种模型",
    tags: ["AI", "网站"],
    icon: "O",
  },
  {
    id: "chatglm",
    name: "智谱清言",
    url: "https://chatglm.cn/",
    category: "AI",
    description: "中文对话与内容生成助手",
    tags: ["AI", "网站"],
    icon: "智",
  },
  {
    id: "yuanbao",
    name: "腾讯元宝",
    url: "https://yuanbao.tencent.com/",
    category: "AI",
    description: "搜索资料与处理文档",
    tags: ["AI", "网站"],
    icon: "腾",
  },
  {
    id: "darktable",
    name: "darktable",
    url: "https://github.com/darktable-org/darktable",
    category: "工具",
    description: "整理和处理摄影原始文件",
    tags: ["工具", "开源"],
    icon: "D",
  },
  {
    id: "buildg",
    name: "buildg",
    url: "https://github.com/ktock/buildg",
    category: "开发",
    description: "逐步调试容器构建过程",
    tags: ["开发", "开源"],
    icon: "B",
  },
  {
    id: "expr",
    name: "Expr",
    url: "https://github.com/expr-lang/expr",
    category: "开发",
    description: "为 Go 应用嵌入表达式计算",
    tags: ["开发", "开源"],
    icon: "E",
  },
  {
    id: "gdu",
    name: "gdu",
    url: "https://github.com/dundee/gdu",
    category: "工具",
    description: "在终端查看磁盘占用",
    tags: ["工具", "开源"],
    icon: "G",
  },
  {
    id: "grapesjs",
    name: "GrapesJS",
    url: "https://github.com/GrapesJS/grapesjs",
    category: "开发",
    description: "构建可视化网页编辑体验",
    tags: ["开发", "开源"],
    icon: "G",
  },
  {
    id: "typedjs",
    name: "Typed.js",
    url: "https://github.com/mattboldt/typed.js",
    category: "开发",
    description: "为网页添加文字输入动画",
    tags: ["开发", "开源"],
    icon: "T",
  },
  {
    id: "buzz",
    name: "Buzz",
    url: "https://github.com/chidiwilliams/buzz",
    category: "AI",
    description: "在本机转录与翻译音频",
    tags: ["AI", "开源"],
    icon: "B",
  },
  {
    id: "mem0",
    name: "Mem0",
    url: "https://github.com/mem0ai/mem0",
    category: "AI",
    description: "为智能体应用管理长期记忆",
    tags: ["AI", "开源"],
    icon: "M",
  },
  {
    id: "defuddle",
    name: "Defuddle",
    url: "https://github.com/kepano/defuddle",
    category: "开发",
    description: "从网页提取主要阅读内容",
    tags: ["开发", "开源"],
    icon: "D",
  },
  {
    id: "dockflare",
    name: "DockFlare",
    url: "https://github.com/ChrispyBacon-dev/DockFlare",
    category: "开发",
    description: "管理容器与 Cloudflare 隧道",
    tags: ["开发", "开源"],
    icon: "D",
  },
  {
    id: "f2",
    name: "F2",
    url: "https://github.com/ayoisaiah/f2",
    category: "工具",
    description: "批量重命名文件并预览结果",
    tags: ["工具", "开源"],
    icon: "F",
  },
  {
    id: "typeid",
    name: "TypeID",
    url: "https://github.com/jetify-com/typeid",
    category: "开发",
    description: "为标识符添加可读类型前缀",
    tags: ["开发", "开源"],
    icon: "T",
  },
  {
    id: "starlight",
    name: "Starlight",
    url: "https://starlight.astro.build/",
    category: "开发",
    description: "基于 Astro 搭建文档站",
    tags: ["开发", "网站"],
    icon: "S",
  },
  {
    id: "ntfy",
    name: "ntfy",
    url: "https://github.com/binwiederhier/ntfy",
    category: "工具",
    description: "通过 HTTP 发布消息通知",
    tags: ["工具", "开源"],
    icon: "N",
  },
  {
    id: "texttosvg",
    name: "Text to SVG",
    url: "https://github.com/JiuRanYa/text-to-svg",
    category: "工具",
    description: "把文字排版导出为 SVG",
    tags: ["工具", "开源"],
    icon: "T",
  },
  {
    id: "smartmermaid",
    name: "Smart Mermaid",
    url: "https://github.com/liujuntao123/smart-mermaid",
    category: "AI",
    description: "通过对话制作 Mermaid 图表",
    tags: ["AI", "开源"],
    icon: "S",
  },
];
