// Selected from the synchronized Chuangzaoshi directory; bundled for offline startup.
import type { Site } from "./model";
export const featuredCatalog: Site[] = [
  {
    id: "czs-f4565e35ccd1e8861ac2f083",
    section: "websites",
    group: "设计",
    name: "Dribbble",
    url: "https://dribbble.com/",
    category: "热门推荐",
    description: "全球UI设计师作品秀社区",
    tags: [],
    icon: "D",
    iconUrl: "/api/navigation?icon=czs-f4565e35ccd1e8861ac2f083",
  },
  {
    id: "czs-a07d0ddb616e128171781325",
    section: "websites",
    group: "设计",
    name: "站酷",
    url: "http://www.zcool.com.cn/",
    category: "热门推荐",
    description: "国内综合设计展示平台",
    tags: [],
    icon: "站",
    iconUrl: "/api/navigation?icon=czs-a07d0ddb616e128171781325",
  },
  {
    id: "czs-66265368449d4419db38df3b",
    section: "websites",
    group: "设计",
    name: "Behance",
    url: "https://www.behance.net/",
    category: "热门推荐",
    description: "Adobe旗下设计师创意视觉社区",
    tags: [],
    icon: "B",
    iconUrl: "/api/navigation?icon=czs-66265368449d4419db38df3b",
  },
  {
    id: "czs-424bf52da0e5b2899c7ca41e",
    section: "websites",
    group: "前端",
    name: "GitHub",
    url: "https://github.com/",
    category: "论坛社区",
    description: "面向开源及私有软件项目的托管平台",
    tags: [],
    icon: "G",
    iconUrl: "/api/navigation?icon=czs-424bf52da0e5b2899c7ca41e",
  },
  {
    id: "czs-9dd9e4bda006e32fe2ce9c55",
    section: "websites",
    group: "前端",
    name: "MDN",
    url: "https://developer.mozilla.org/zh-CN/",
    category: "学习平台",
    description: "开发者网络(MDN)提供有关开放网络技术",
    tags: [],
    icon: "m",
    iconUrl: "/api/navigation?icon=czs-9dd9e4bda006e32fe2ce9c55",
  },
  {
    id: "czs-4b258db183fda314e5609a41",
    section: "websites",
    group: "前端",
    name: "CodePen",
    url: "http://codepen.io/",
    category: "热门推荐",
    description: "前端炫酷样式技能效果",
    tags: [],
    icon: "c",
    iconUrl: "/api/navigation?icon=czs-4b258db183fda314e5609a41",
  },
  {
    id: "czs-f934ead9a3a9e15dcb10d746",
    section: "websites",
    group: "产品",
    name: "Product Hunt",
    url: "https://www.producthunt.com/",
    category: "新品推荐",
    description: "全球最新潮的科技类新品站",
    tags: [],
    icon: "P",
    iconUrl: "/api/navigation?icon=czs-f934ead9a3a9e15dcb10d746",
  },
  {
    id: "czs-e7b6987d385abb4a4ba85edc",
    section: "websites",
    group: "产品",
    name: "少数派",
    url: "http://sspai.com/",
    category: "产品资讯",
    description: "专注于移动APP编辑精选",
    tags: [],
    icon: "少",
    iconUrl: "/api/navigation?icon=czs-e7b6987d385abb4a4ba85edc",
  },
  {
    id: "czs-d70db09f459a58ff390db691",
    section: "websites",
    group: "产品",
    name: "V2EX",
    url: "https://www.v2ex.com/?tab=creative",
    category: "新品推荐",
    description: "V2EX创意新品和项目分享节点",
    tags: [],
    icon: "V",
    iconUrl: "/api/navigation?icon=czs-d70db09f459a58ff390db691",
  },
  {
    id: "czs-83b07b11c6be4539a877a1c1",
    section: "websites",
    group: "运营",
    name: "百度指数",
    url: "http://index.baidu.com/",
    category: "数据分析",
    description: "百度互联网数据分享平台",
    tags: [],
    icon: "百",
    iconUrl: "/api/navigation?icon=czs-83b07b11c6be4539a877a1c1",
  },
  {
    id: "czs-982cac2f2a1b0c476ce3d974",
    section: "websites",
    group: "运营",
    name: "Google 趋势",
    url: "https://www.google.com/trends/",
    category: "数据分析",
    description: "google数据和图表了解全球热度",
    tags: [],
    icon: "G",
    iconUrl: "/api/navigation?icon=czs-982cac2f2a1b0c476ce3d974",
  },
  {
    id: "czs-a3b9b92073d85050a5faaba4",
    section: "websites",
    group: "运营",
    name: "Similarweb",
    url: "https://www.similarweb.com/",
    category: "数据分析",
    description: "好用的网站排名丨流量数据分析",
    tags: [],
    icon: "S",
    iconUrl: "/api/navigation?icon=czs-a3b9b92073d85050a5faaba4",
  },
  {
    id: "czs-2ab3b5fc19977430eb829a71",
    section: "websites",
    group: "设计",
    name: "创客贴",
    url: "https://www.chuangkit.com/",
    category: "热门推荐",
    description: "免费在线平面设计工具",
    tags: [],
    icon: "创",
    iconUrl: "/api/navigation?icon=czs-2ab3b5fc19977430eb829a71",
  },
  {
    id: "czs-cb56bd58797b0985624b839b",
    section: "websites",
    group: "设计",
    name: "Adobe Color",
    url: "https://color.adobe.com/",
    category: "热门推荐",
    description: "非常便捷的在线配色网站",
    tags: [],
    icon: "A",
    iconUrl: "/api/navigation?icon=czs-cb56bd58797b0985624b839b",
  },
  {
    id: "czs-f4ed6fe32dfb92a5dc813e72",
    section: "websites",
    group: "前端",
    name: "W3Schools",
    url: "http://www.w3schools.com/",
    category: "热门推荐",
    description: "WEB初学者教程网站",
    tags: [],
    icon: "w",
    iconUrl: "/api/navigation?icon=czs-f4ed6fe32dfb92a5dc813e72",
  },
  {
    id: "czs-9b1e3bb95895d8fad568d01e",
    section: "websites",
    group: "前端",
    name: "Bootstrap",
    url: "http://getbootstrap.com/",
    category: "热门推荐",
    description: "用于前端开发的开源工具包",
    tags: [],
    icon: "B",
    iconUrl: "/api/navigation?icon=czs-9b1e3bb95895d8fad568d01e",
  },
  {
    id: "czs-8fbe72e0958b68e27a42c04b",
    section: "websites",
    group: "产品",
    name: "36氪",
    url: "http://36kr.com/",
    category: "产品资讯",
    description: "为创业者提供最好的产品和服务",
    tags: [],
    icon: "3",
    iconUrl: "/api/navigation?icon=czs-8fbe72e0958b68e27a42c04b",
  },
  {
    id: "czs-e7fd558387cdb54d05b5f14b",
    section: "websites",
    group: "运营",
    name: "站长工具",
    url: "http://tool.chinaz.com/",
    category: "数据分析",
    description: "站长工具数据查询网站",
    tags: [],
    icon: "站",
    iconUrl: "/api/navigation?icon=czs-e7fd558387cdb54d05b5f14b",
  },
];
